version: "3"
services:
 
    statistics-service-api:
        build: ./statistics-service/api
        restart: always
        ports:
            - 6001:80
        networks:
            - frontend
            - backend

    statistics_service_worker:
        build: ./statistics-service/worker
        restart: always
        networks:
            - frontend
            - backend

    statistics-service-redis:
        image: redis:alpine
        restart: always
        ports:
            - 6379:6379
        networks:
            - frontend

    statistics-service-db:
        image: postgres:9.4
        restart: always
        volumes:
            - db-data:/var/lib/postgresql/data
        networks:
            - backend
        environment:
            POSTGRES_HOST_AUTH_METHOD: trust

    product-service-api:
        build: ./product-service/api
        restart: always
        ports:
            - 7001:8080
        networks:
            - frontend
            - backend

    account-service-api:
        build: ./account-service/api
        restart: always
        ports:
            - 7002:8080
        networks:
            - frontend
            - backend

    product-service-db:
        image: mysql:5.6
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        volumes:
            - ./product-service/api/scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
        ports:
            - 3306:3306
        environment:
          MYSQL_ROOT_PASSWORD: P2ssw0rd
        networks:
            - frontend
            - backend

    phpmyadmin:
        image: phpmyadmin:5.0.4-apache
        restart: always
        ports:
            - 8080:80
        environment:
            - PMA_ARBITRARY=1
        networks:
            - frontend
            - backend

networks:
    frontend:
    backend:

volumes:
    db-data: